
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jul 01 16:41:50 ART 2020
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CierreDeItemEnLaLista = 51;
  public static final int AperturaDivision = 30;
  public static final int AperturaBodyConAtributo = 76;
  public static final int AperturaSeccionConAtributo = 97;
  public static final int CierreTitulo = 16;
  public static final int CierreDivision = 31;
  public static final int Atributowidth = 70;
  public static final int FinMarcadoConEnfasis = 24;
  public static final int AperturaEtiquetaAconAtributo = 6;
  public static final int CierreDeCelda = 64;
  public static final int AperturaTitulo6ConAtributo = 85;
  public static final int InicioDeParrafoConAtributo = 99;
  public static final int AperturaTitulo2ConAtributo = 81;
  public static final int Imagen = 8;
  public static final int InicioDeTituloDeTablaConAtributo = 90;
  public static final int FinResaltadoEm = 26;
  public static final int InicioDeCabezaDeTablaConAtributo = 91;
  public static final int AtributogeneralID = 105;
  public static final int SaltoDeLinea = 22;
  public static final int InicioDeCabezaDeTabla = 57;
  public static final int ItemEnLaLista = 50;
  public static final int AperturaListaDesordenada = 48;
  public static final int InicioDeParrafo = 20;
  public static final int FinDeCuerpoDeTabla = 62;
  public static final int Url = 73;
  public static final int InicioDeColumnaConAtributo = 95;
  public static final int InicioResaltadoEm = 25;
  public static final int InicioMarcadoConEnfasis = 23;
  public static final int ERROR = 106;
  public static final int AperturaDeIdiomaHTML = 74;
  public static final int AtributoTARGET = 103;
  public static final int FinResaltadoMark = 28;
  public static final int AperturaDeListaOrdenadaConAtributo = 86;
  public static final int CierreEtiquetaA = 7;
  public static final int AperturaTitulo3ConAtributo = 82;
  public static final int InicioDePieDeTabla = 59;
  public static final int CierreDeColumna = 66;
  public static final int InicioDeColumna = 65;
  public static final int AtributogeneralCLASS = 104;
  public static final int InicioResaltadoEmConAtributo = 79;
  public static final int Atributoheight = 71;
  public static final int CierreTitulo6 = 45;
  public static final int CierreTitulo5 = 43;
  public static final int CierreTitulo4 = 41;
  public static final int AperturaDivisionConAtributo = 78;
  public static final int CierreTitulo3 = 39;
  public static final int AperturaListaDesordenadaConAtributo = 87;
  public static final int CierreTitulo2 = 37;
  public static final int CierreDeDocumento = 11;
  public static final int CierreTitulo1 = 35;
  public static final int InicioDeCeldaConAtributo = 94;
  public static final int UnaLineaHorizontal = 19;
  public static final int CierreBody = 18;
  public static final int InicioDocumento = 10;
  public static final int FinDeParrafo = 21;
  public static final int CierreDeFila = 68;
  public static final int CierreDeCabezaDeTabla = 58;
  public static final int AperturaLibreriaHTML = 9;
  public static final int CierreHead = 13;
  public static final int InicioDeTabla = 53;
  public static final int Atributosrc = 69;
  public static final int CierreSeccion = 33;
  public static final int texto = 98;
  public static final int AperturaTitulo4ConAtributo = 83;
  public static final int AtributoHREF = 102;
  public static final int AperturaDeListaOrdenada = 46;
  public static final int InicioDeTituloDeTabla = 55;
  public static final int EOF = 0;
  public static final int AperturaTitulo6 = 44;
  public static final int AperturaTitulo5 = 42;
  public static final int AperturaBody = 17;
  public static final int AperturaTitulo4 = 40;
  public static final int CierreListaDesordenada = 49;
  public static final int AperturaTitulo3 = 38;
  public static final int AperturaTitulo2 = 36;
  public static final int FinDePieDeTabla = 60;
  public static final int InicioDeCuerpoDeTablaConAtributo = 93;
  public static final int AperturaTitulo1 = 34;
  public static final int AperturaSeccion = 32;
  public static final int InicioDeTablaConAtributo = 2;
  public static final int error = 1;
  public static final int AperturaHead = 12;
  public static final int AperturaMetaNameConAtributo = 3;
  public static final int InicioMarcadoConEnfasisConAtributo = 77;
  public static final int CierreDeTabla = 54;
  public static final int alt = 72;
  public static final int TablaConBordeConAtributo = 89;
  public static final int AperturaTitle = 15;
  public static final int ItemEnLaListaConAtributo = 88;
  public static final int CierreDeListaOrdenada = 47;
  public static final int AperturaTitulo5ConAtributo = 84;
  public static final int AperturaMetaName = 14;
  public static final int AperturaTitleConAtributo = 75;
  public static final int AperturaTitulo1ConAtributo = 80;
  public static final int FinEtiqueta = 5;
  public static final int InicioResaltadoMarkConAtributo = 29;
  public static final int InicioDeCelda = 63;
  public static final int InicioDePieDeTablaConAtributo = 92;
  public static final int InicioDeCuerpoDeTabla = 61;
  public static final int InicioResaltadoMark = 27;
  public static final int InicioDefila = 67;
  public static final int VALUE = 101;
  public static final int LATE = 100;
  public static final int EspacioVacio = 4;
  public static final int TablaConBorde = 52;
  public static final int FinDeTituloDeTabla = 56;
  public static final int InicioDefilaConAtributo = 96;
}

